### ISSUE TITLE
New Track not loading

### ISSUE THREAD

**Issue by ChristopherGogl** [f1tenth-dev/tutorials#3]
Hi
I was trying the expert tutorial to add a custom track.
I created the stl file as explained. But the new track is not going to be loaded.
Inside the race_track.world i replaced the filename to load. Even if I try to replace the existing stl file it is not going to be loaded.

For creating the track I used FreeCAD and tried also with SolidWorks. Both generated Files are not Loaded.

Gazebo is able to start anyway but clicking the at the track entry in the model tree results in a crash of Gazebo.
```
[gazebo_gui-5] process has died [pid 3065, exit code 134, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient map:=/map __name:=gazebo_gui __log:=/home/robolab/.ros/log/ceeae984-4c26-11eb-b925-00e04c102ad8/gazebo_gui-5.log].
log file: /home/robolab/.ros/log/ceeae984-4c26-11eb-b925-00e04c102ad8/gazebo_gui-5*.log
```
The log file doesn't exist so I don't know what it tried to say.

Now I'm wondering if the stl file is not correct or if i messed it up somewhere else.
The track should be a free area with some borders that the car won't fall down.

Attached you can find the stl files I have tried.
[tracks.zip](https://github.com/f1tenth-dev/tutorials/files/5758885/tracks.zip)

**Comment by mariusrodi** [comment]
I am having the same problem with a world created in Creo.

Attached you can find the world setup I used:
[world.zip](https://github.com/f1tenth-dev/tutorials/files/5760133/world.zip)

**Comment by ChristopherGogl** [comment]
I found it out myself and feel a little bit stupid right now.
The stl file and everything else was correct. 
The only thing i forgot was to add the files also in .gazebo/models.
After i added the stl file there too everything worked fine for me.
